# Generated by Django 5.2.5 on 2025-08-29 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_seats',
            new_name='num_passengers',
        ),
    ]
